package com.team418.domain;

public enum Feature {
    CREATE_LIBRARIAN,
    REGISTER_NEW_BOOK,
    UPDATE_BOOK,
    REGISTER_NEW_LENDING,
    RETURN_lENDED_BOOK,
    DELETE_BOOK,
    VIEW_DELETED_BOOK,
    RESTORE_BOOK
}
